### ISSUE TITLE
Regex issue when multiple param in path

### ISSUE THREAD

**Issue by icelynde** [ShanaMaid/koa-swagger-mock#2]
Hi,

great npm package but found an issue when having multiple parameter in path like this uri `/v1/programs/{programId2}/mediums/{mediumId2}/balance`.
It will replace it by `/v1/programs/:programId2}/mediums/{mediumId2/balance` instead of `/v1/programs/:programId2/mediums/:mediumId2/balance`

if you change this line https://github.com/ShanaMaid/koa-swagger-mock/blob/0aac4aeff8bf12e0b59ffe25c16a59b7162cbdbc/lib/koa-swagger-mock.js#L15 by `const url = origin.replace(/\{(.*?)\}/g, ':$1');` it works fine.

**Comment by ShanaMaid** [comment]
@icelynde  ok， thanks for your issue. 
I have publish `2.0.1`.
